package goblinlabour.client;

import goblinlabour.GoblinLabour;
import goblinlabour.entity.GoblinEntity;
import goblinlabour.entity.GoblinStyle;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.HumanoidMobRenderer;
import net.minecraft.resources.Identifier;

public class GoblinRenderer extends HumanoidMobRenderer<GoblinEntity, GoblinRenderState, GoblinModel> {
    /** textures/entity/goblin_&lt;style&gt;_&lt;look&gt;.png, generated by tools/MakeGoblinTexture.java. */
    private static final Identifier[][] TEXTURES = new Identifier[GoblinStyle.values().length][GoblinStyle.LOOKS];

    static {
        for (GoblinStyle style : GoblinStyle.values()) {
            for (int look = 0; look < GoblinStyle.LOOKS; look++) {
                TEXTURES[style.ordinal()][look] = GoblinLabour.id(
                        "textures/entity/goblin_" + style.getSerializedName() + "_" + look + ".png");
            }
        }
    }

    public GoblinRenderer(EntityRendererProvider.Context context) {
        super(context, new GoblinModel(context.bakeLayer(GoblinLabourClient.GOBLIN_LAYER)), 0.35f);
    }

    @Override
    public GoblinRenderState createRenderState() {
        return new GoblinRenderState();
    }

    @Override
    public void extractRenderState(GoblinEntity goblin, GoblinRenderState state, float partialTick) {
        super.extractRenderState(goblin, state, partialTick);
        state.style = goblin.getStyle();
        state.look = GoblinStyle.lookFor(goblin.goblinName());
    }

    @Override
    public Identifier getTextureLocation(GoblinRenderState state) {
        return TEXTURES[state.style.ordinal()][state.look];
    }
}
