package goblinlabour.client;

import com.mojang.blaze3d.vertex.PoseStack;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.HumanoidRenderState;
import net.minecraft.world.entity.HumanoidArm;

/**
 * A hunched goblin: big head with long pointed ears and a hooked nose, open leather vest, loincloth, long arms,
 * short legs and big feet. Built as a plain humanoid model so vanilla's walk, swing and item-in-hand code work
 * unchanged. HumanoidModel resets part positions every frame, so the goblin proportions are re-applied after
 * {@link HumanoidModel#setupAnim}. Texture: 64x64, generated by {@code tools/MakeGoblinTexture.java}, which uses the
 * same texture offsets as this class.
 */
public class GoblinModel extends HumanoidModel<GoblinRenderState> {
    private static final float BODY_TILT = 0.07f;
    private static final float HEAD_TILT = -0.05f;
    private static final float ARM_TILT = -0.09f;
    /** Held items are drawn smaller so a pickaxe does not look like a player's in a goblin's fist. */
    private static final float HELD_ITEM_SCALE = 0.75f;

    private static final float HIP_Y = 20.0f;
    private static final float NECK_Y = 14.0f;
    /** The torso leans forward slightly, so its top (neck and shoulders) sits half a pixel in front of the hips. */
    private static final float NECK_Z = -0.5f;

    /** Hair knot with a braid down the back of the head; only look 3 wears it. */
    private static final int TOPKNOT_LOOK = 3;

    private final ModelPart topknot;

    public GoblinModel(ModelPart root) {
        super(root);
        topknot = head.getChild("topknot");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body",
                CubeListBuilder.create()
                        .texOffs(0, 14).addBox(-3.0f, -6.0f, -2.0f, 6.0f, 6.0f, 4.0f)
                        .texOffs(20, 14).addBox(-3.0f, -6.0f, -2.0f, 6.0f, 6.0f, 4.0f, new CubeDeformation(0.3f))
                        .texOffs(40, 18).addBox(-3.0f, -1.0f, -2.0f, 6.0f, 1.0f, 4.0f, new CubeDeformation(0.4f)),
                PartPose.offsetAndRotation(0.0f, HIP_Y, 0.0f, BODY_TILT, 0.0f, 0.0f));
        // hangs straight down from the hips, whatever the torso does
        body.addOrReplaceChild("loincloth",
                CubeListBuilder.create()
                        .texOffs(48, 24).addBox(-2.0f, 0.0f, -2.6f, 4.0f, 3.0f, 0.0f)
                        .texOffs(48, 27).addBox(-2.0f, 0.0f, 2.6f, 4.0f, 3.0f, 0.0f),
                PartPose.rotation(-BODY_TILT, 0.0f, 0.0f));

        PartDefinition head = root.addOrReplaceChild("head",
                CubeListBuilder.create().texOffs(0, 0).addBox(-4.0f, -7.0f, -3.0f, 8.0f, 7.0f, 6.0f),
                PartPose.offsetAndRotation(0.0f, NECK_Y, NECK_Z, HEAD_TILT, 0.0f, 0.0f));
        head.addOrReplaceChild("hat", CubeListBuilder.create(), PartPose.ZERO);
        head.addOrReplaceChild("topknot",
                CubeListBuilder.create()
                        .texOffs(28, 0).addBox(-1.0f, -9.0f, 1.0f, 2.0f, 2.0f, 2.0f)
                        .texOffs(36, 0).addBox(-0.5f, -8.0f, 3.0f, 1.0f, 4.0f, 1.0f),
                PartPose.ZERO);
        head.addOrReplaceChild("nose",
                CubeListBuilder.create()
                        .texOffs(40, 24).addBox(-1.0f, -4.0f, -5.0f, 2.0f, 2.0f, 2.0f)
                        .texOffs(40, 28).addBox(-1.0f, -2.0f, -5.0f, 2.0f, 1.0f, 1.0f),
                PartPose.ZERO);
        // ears taper to a point and sweep back and up
        head.addOrReplaceChild("left_ear",
                CubeListBuilder.create()
                        .texOffs(32, 24).addBox(0.0f, 0.0f, 0.0f, 2.0f, 3.0f, 1.0f)
                        .texOffs(32, 28).addBox(2.0f, 0.0f, 0.0f, 2.0f, 2.0f, 1.0f)
                        .texOffs(32, 31).addBox(4.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f),
                PartPose.offsetAndRotation(4.0f, -5.0f, 0.0f, 0.0f, -0.5f, -0.25f));
        head.addOrReplaceChild("right_ear",
                CubeListBuilder.create().mirror()
                        .texOffs(32, 24).addBox(-2.0f, 0.0f, 0.0f, 2.0f, 3.0f, 1.0f)
                        .texOffs(32, 28).addBox(-4.0f, 0.0f, 0.0f, 2.0f, 2.0f, 1.0f)
                        .texOffs(32, 31).addBox(-6.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f),
                PartPose.offsetAndRotation(-4.0f, -5.0f, 0.0f, 0.0f, 0.5f, 0.25f));

        root.addOrReplaceChild("right_arm",
                CubeListBuilder.create().texOffs(0, 24).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 7.0f, 2.0f),
                PartPose.offsetAndRotation(-4.0f, NECK_Y, NECK_Z, ARM_TILT, 0.0f, 0.0f));
        root.addOrReplaceChild("left_arm",
                CubeListBuilder.create().texOffs(8, 24).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 7.0f, 2.0f),
                PartPose.offsetAndRotation(4.0f, NECK_Y, NECK_Z, ARM_TILT, 0.0f, 0.0f));

        root.addOrReplaceChild("right_leg",
                CubeListBuilder.create()
                        .texOffs(16, 24).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 4.0f, 2.0f)
                        .texOffs(16, 30).addBox(-1.0f, 3.0f, -2.0f, 2.0f, 1.0f, 1.0f),
                PartPose.offset(-1.5f, HIP_Y, 0.0f));
        root.addOrReplaceChild("left_leg",
                CubeListBuilder.create()
                        .texOffs(24, 24).addBox(-1.0f, 0.0f, -1.0f, 2.0f, 4.0f, 2.0f)
                        .texOffs(24, 30).addBox(-1.0f, 3.0f, -2.0f, 2.0f, 1.0f, 1.0f),
                PartPose.offset(1.5f, HIP_Y, 0.0f));

        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public void setupAnim(GoblinRenderState state) {
        super.setupAnim(state);
        topknot.visible = state.look == TOPKNOT_LOOK;
        body.setPos(0.0f, HIP_Y, 0.0f);
        body.xRot = BODY_TILT;
        head.setPos(0.0f, NECK_Y, NECK_Z);
        head.xRot += HEAD_TILT;
        rightArm.setPos(-4.0f, NECK_Y, NECK_Z);
        leftArm.setPos(4.0f, NECK_Y, NECK_Z);
        rightArm.xRot += ARM_TILT;
        leftArm.xRot += ARM_TILT;
        rightLeg.setPos(-1.5f, HIP_Y, 0.0f);
        leftLeg.setPos(1.5f, HIP_Y, 0.0f);
    }

    @Override
    public void translateToHand(HumanoidRenderState state, HumanoidArm arm, PoseStack poseStack) {
        super.translateToHand(state, arm, poseStack);
        // Goblin arms are 2 px wide and centred on the shoulder, and end 3 px higher than a player's hand. The item
        // layer's own offsets (1 px sideways, 10 px down the arm) are applied after the scale, so the translation
        // here only makes up the difference: 7 px - 10 px * scale down the arm, 1 px * scale sideways.
        float side = 0.0625f * HELD_ITEM_SCALE;
        poseStack.translate(arm == HumanoidArm.LEFT ? -side : side, (7.0f - 10.0f * HELD_ITEM_SCALE) / 16.0f - 0.03f, 0.0f);
        poseStack.scale(HELD_ITEM_SCALE, HELD_ITEM_SCALE, HELD_ITEM_SCALE);
    }
}
